### PR TITLE
AJ-1011: openapi cleanup

### PR DESCRIPTION
**Pull request by davidangb**
Prefactoring for AJ-1011. In `service/src/main/resources/static/swagger/openapi-docs.yaml`:

* clean up some formatting
* add some code comments
* sort paths first by their tag (Records, Schema, Instances, etc) and second alphabetically
* sort all components alphabetically

A lot of lines of code have changed, but there should be zero functional changes; it's all reordering and formatting. You can view commit-by-commit to see it in smaller chunks.

### CODE REVIEW

**Review by calypsomatic — COMMENTED** [review]
While you're at it, can you put the API name over on the right side, like here? 
image

**Comment by davidangb** [comment]
> While you're at it, can you put the API name over on the right side, like here? image

@calypsomatic I did that back in #331! Note that you'll only see it when hitting the UI from a running WDS; you won't see it when viewing the spec via https://petstore.swagger.io/ - because the change is specific to the HTML/JS that interprets the spec.

**Review by jladieu — APPROVED** [review]
Lookin' good!

**Comment by calypsomatic** [comment]
> @calypsomatic I did that back in #331! Note that you'll only see it when hitting the UI from a running WDS; you won't see it when viewing the spec via https://petstore.swagger.io/ - because the change is specific to the HTML/JS that interprets the spec.
Huh!

**Review by calypsomatic — APPROVED** [review]

**Pull request merged**
