### PR TITLE
[AJ-1782] Address dnsjava vulnerability

### PR DESCRIPTION
**Pull request by calypsomatic**
Addresses https://github.com/DataBiosphere/terra-workspace-data-service/security/dependabot/95

Reminder:

#### Releasing WDS ####
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag-and-publish.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the action will not fully succeed. 

After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged successfully.

The terra-helmfile PR merge will then generate a PR in [leonardo](https://github.com/DataBiosphere/leonardo).  This will automerge if all tests pass, but if jenkins tests fail it will not; be sure to watch it to ensure it merges. To trigger jenkins retest simply comment on PR with "jenkins retest". 

#### Keeping Docs Up To Date ####
If you make changes to the github actions or workflows, particularly when they are run or which other workflows they call, please update [the GHA wiki page](https://github.com/DataBiosphere/terra-workspace-data-service/wiki/GHA-structure-in-WDS) to stay up to date.

### CODE REVIEW

**Review by davidangb — APPROVED** [review]
:+1: for syntax

This could use AJ-1782, probably doesn't need its own ticket

I am curious if you can exclude `dnsjava` via `withoutHadoopExcludes` [here](https://github.com/DataBiosphere/terra-workspace-data-service/blob/09445abb939834d5a39589c5f0f33087386eba0f/service/build.gradle#L105-L119) instead of updating it, or if it's really necessary for functionality

**Comment by calypsomatic** [comment]
> I am curious if you can exclude `dnsjava` via `withoutHadoopExcludes` [here](https://github.com/DataBiosphere/terra-workspace-data-service/blob/09445abb939834d5a39589c5f0f33087386eba0f/service/build.gradle#L105-L119) instead of updating it, or if it's really necessary for functionality

The tests passed and bootRun started up when I excluded it; what should I explicitly test to verify we don't need is?

**Comment by davidangb** [comment]
> what should I explicitly test to verify we don't need it?

@calypsomatic try running a real import into a locally-running WDS? If tests pass I'm pretty sure we're good, but a manual smoke test would be great

**Comment by calypsomatic** [comment]
> > what should I explicitly test to verify we don't need it?
> 
> @calypsomatic try running a real import into a locally-running WDS? If tests pass I'm pretty sure we're good, but a manual smoke test would be great

Seems to work!

**Review by davidangb — APPROVED** [review]
reiterating :+1:

**Review by mspector — APPROVED** [review]

**Pull request merged**
