### PR TITLE
Demo publishing multiple pacts. DO NOT MERGE!

### PR DESCRIPTION
**Pull request by ichengchang**
Reminder:

PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the action will not fully succeed. 

After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged successfully.

The terra-helmfile PR merge will then generate a PR in [leonardo](https://github.com/DataBiosphere/leonardo).  This will automerge if all tests pass, but if jenkins tests fail it will not; be sure to watch it to ensure it merges. To trigger jenkins retest simply comment on PR with "jenkins retest".

### CODE REVIEW

**Review by jladieu — CHANGES_REQUESTED** [review]
Ok I had a chance to try this out...what I did was copy paste the freshest copy of the pact.yml file you were editing from the tip of the branch you posted.

Then I tried it in place to make sure it worked with the existing single consumer/provider pair (it did).

Then I played my change on top of it and pushed up PR, which adds another consumer/provider pair, and re-kicked it to get

https://github.com/DataBiosphere/terra-workspace-data-service/actions/runs/6733845407/job/18303607419?pr=399

My initial feedback/observation:
* `run-consumer-contract-tests` correctly writes out two pactfiles `build/pacts/wds-workspacemanager.json` and `build/pacts/sam.json`
* `publish-pacts-job` gets kicked off twice (which seems correct), but appears to produce identical dispatches which each _only_ publish the sam/wds contract: https://github.com/broadinstitute/terra-github-workflows/actions/runs/6733906633
* I'm guessing some of the bash logic unintentionally reuses the same b64 instead of producing a novel one for each pactfile.

**Comment by ichengchang** [comment]
> Ok I had a chance to try this out...what I did was copy paste the freshest copy of the pact.yml file you were editing from the tip of the branch you posted.
> 
> Then I tried it in place to make sure it worked with the existing single consumer/provider pair (it did).
> 
> Then I played my change on top of it and pushed up PR, which adds another consumer/provider pair, and re-kicked it to get
> 
> https://github.com/DataBiosphere/terra-workspace-data-service/actions/runs/6733845407/job/18303607419?pr=399
> 
> My initial feedback/observation:
> 
>     * `run-consumer-contract-tests` correctly writes out two pactfiles `build/pacts/wds-workspacemanager.json` and `build/pacts/sam.json`
> 
>     * `publish-pacts-job` gets kicked off twice (which seems correct), but appears to produce identical dispatches which each _only_ publish the sam/wds contract: https://github.com/broadinstitute/terra-github-workflows/actions/runs/6733906633
> 
>     * I'm guessing some of the bash logic unintentionally reuses the same b64 instead of producing a novel one for each pactfile.

We need to provide each run in the matrix a unique run name, otherwise it appear to be run once in `terra-github-workflows`. I have updated the code to use the path of the pact file in the run name, that ensures these runs will appear separately in `terra-github-workflows`.

**Comment by jladieu** [comment]
This was incorporated into https://github.com/DataBiosphere/terra-workspace-data-service/pull/399 -- I think it's safe to close this PR out now, but I'll defer to @ichengchang to do that.

**Comment by jladieu** [comment]
It's been three weeks so I'm gonna close this out.

**Pull request closed without merging**
