### PR TITLE
AJ-1743 fix WSM pact

### PR DESCRIPTION
**Pull request by calypsomatic**
The pact between WSM and WDS is [failing](https://pact-broker.dsp-eng-tools.broadinstitute.org/hal-browser/browser.html#/pacts/provider/workspacemanager/consumer/wds/pact-version/2cebab3d7090679e5aa97b996cfc47f0db59e748/verification-results/10305).  I see the message "Expected [{\"key\":\"key\",\"value\":\"purpose\"}, {\"key\":\"value\",\"value\":\"policy\"}] to have maximum 1", Attempting to fix that.

Reminder:

#### Releasing WDS ####
PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag-and-publish.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the action will not fully succeed. 

After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged successfully.

The terra-helmfile PR merge will then generate a PR in [leonardo](https://github.com/DataBiosphere/leonardo).  This will automerge if all tests pass, but if jenkins tests fail it will not; be sure to watch it to ensure it merges. To trigger jenkins retest simply comment on PR with "jenkins retest". 

#### Keeping Docs Up To Date ####
If you make changes to the github actions or workflows, particularly when they are run or which other workflows they call, please update [the GHA wiki page](https://github.com/DataBiosphere/terra-workspace-data-service/wiki/GHA-structure-in-WDS) to stay up to date.

### CODE REVIEW

**Review by jladieu — APPROVED** [review]

**Review by nawatts — CHANGES_REQUESTED** [review]
> Expected [{"key":"key","value":"purpose"}, {"key":"value","value":"policy"}] to have maximum 1"

It's not the length requirement that's incorrect, it's the content of that array.

That should be `[{"key":"purpose","value":"policy"}]`

**Comment by calypsomatic** [comment]
> > Expected [{"key":"key","value":"purpose"}, {"key":"value","value":"policy"}] to have maximum 1"
> 
> It's not the length requirement that's incorrect, it's the content of that array.
> 
> That should be `[{"key":"purpose","value":"policy"}]`

That was my first thought, but then I convinced myself that it was just representing it a weird way, but you're probably right.

**Review by nawatts — APPROVED** [review]
Nit: the PR title is inaccurate now

**Comment by calypsomatic** [comment]
> > Expected [{"key":"key","value":"purpose"}, {"key":"value","value":"policy"}] to have maximum 1
> 
> It's not the length requirement that's incorrect, it's the content of that array.
> 
> It should be `[{"key":"purpose","value":"policy"}]`

@nawatts Huh I thought I updated it to do that but now I'm getting the error "ERROR au.com.dius.pact.consumer.BaseMockServer$Companion -- PartialRequestMatch: a request to create a snapshot reference:
        Expected a Map with keys [purpose] but received one with keys [key, value]".  I'm very confused.  @jladieu you know about the PactDSL can you help?

**Review by nawatts — CHANGES_REQUESTED** [review]
> PartialRequestMatch: a request to create a snapshot reference:
Expected a Map with keys [purpose] but received one with keys [key, value]

Ok, sounds like the expectation is incorrect now. The expected keys are "key" and "value".

**Comment by calypsomatic** [comment]
> > PartialRequestMatch: a request to create a snapshot reference:
> > Expected a Map with keys [purpose] but received one with keys [key, value]
> 
> Ok, sounds like the expectation is incorrect now. The expected keys are "key" and "value".

Still confused.  Is this expectation coming from WSM?  Do we need to update pact verification [there](https://github.com/DataBiosphere/terra-workspace-manager/blob/1a915c1c51b4a27b48d68bb71add65f280a18682/service/src/test/java/bio/terra/workspace/pact/WdsContractVerificationTest.java#L292)?  Except that it's failing at the unit test stage, which presumably is before we contact WSM at all?

**Review by nawatts — APPROVED** [review]

**Comment by nawatts** [comment]
After further investigation, it looks like the issue is on the WSM side in the mock response
https://github.com/DataBiosphere/terra-workspace-manager/pull/1708

**Comment by calypsomatic** [comment]
The problem was on the WSM side.

**Pull request closed without merging**
